In [1]:
import numpy as np
inputs = np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])
weights = np.array([
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
])

biases = np.array([2,3,0.5])

weights2 = np.array([
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]
])

biases2 = np.array([-1,2,-0.5])

layer1_output = np.dot(inputs, weights.T) + biases
layer2_output = np.dot(layer1_output, weights2.T) + biases2

print(layer1_output)
print(layer2_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [27]:
np.random.seed(0)
X = np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

layer_1 = Layer_Dense(4, 5)
layer_2 = Layer_Dense(5, 2)

layer_1.forward(X)
# print(layer_1.outputs)
layer_2.forward(layer_1.outputs)
print(layer_2.outputs)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [28]:
A = np.array([
    [2,5,1,6,7],
    [-4,9,1,-8,5],
    [7,6,1,3,-2],
    [-2,-9,7,5,8]
])

np.random.seed(0)
class Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10*np.random.rand(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

layer_1 = Dense(5, 7)
layer_2 = Dense(7, 8)
layer_3 = Dense(8, 10)

layer_1.forward(A)
layer_2.forward(layer_1.outputs)
layer_3.forward(layer_2.outputs)
print(layer_3.outputs)

[[0.15251755 0.15760242 0.20521584 0.15056938 0.181393   0.11523887
  0.14422844 0.17496892 0.1340901  0.16158616]
 [0.0267473  0.02794015 0.03211413 0.02685247 0.03140848 0.01750315
  0.02271157 0.03036328 0.01849906 0.02829836]
 [0.12570865 0.12825643 0.16831833 0.12245684 0.14811925 0.09641914
  0.11841789 0.14301661 0.11045977 0.13225944]
 [0.02663507 0.02876644 0.03972492 0.02665303 0.03549947 0.01727638
  0.02740369 0.03113142 0.02414402 0.02811193]]
