In [1]:
# raw implementation first
import numpy as np
layer_outputs = [
    [4.8, 1.21, 2.385],
    [8.9, -1.81, 0.2],
    [1.41, 1.051, 0.026]
]

exp_values = np.exp(layer_outputs)

# axis parameter 0 sums up all the values in the same column and axis 1 sums up all the values in the same row
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)

print(np.sum(exp_values, axis=1, keepdims=True))
print(norm_values)
print(np.sum(norm_values, axis=1, keepdims=True))

[[ 135.72296484]
 [7333.35859605]
 [   7.98280655]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
[[1.]
 [1.]
 [1.]]


In [ ]:
# it's implementation time

import numpy as np
import nnfs 
from nnfs.datasets import spiral_data

nnfs.init()

np.random.seed(0)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = norm_values

X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])
print(np.sum(activation2.output[:5], axis=1, keepdims=True))

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
