# Intro
Shows all the basic codes for numpy ndarrays

In [2]:
#note: to access the python venv first
#Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
#and then .\.venv\Scripts\Activate.ps1
import numpy as np

In [3]:
print("Numpy version: ", np.__version__) #shows the version of numpy

Numpy version:  2.3.1


In [2]:
arr = np.array([1,2,3,4,5])
print("Test array: ", arr) #easily prints it out

Test array:  [1 2 3 4 5]


In [4]:
a = np.array([3,2,8,1,9]) #1 dimensional array
b = np.array([[4,3,2],[6,1,1]]) #2 dimensional array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3 dimensional array

# ndim prints the dimension of an array
print("A array dimension: ", a.ndim) #1
print("B array dimension: ", b.ndim) #2
print("C array dimension: ", c.ndim) #3

A array dimension:  1
B array dimension:  2
C array dimension:  3


In [5]:
d = np.array([1,2,3,4,5], ndmin=5) #you can verify how many dimensions an array has

print("D array with 5 dimensions: ", d)

D array with 5 dimensions:  [[[[[1 2 3 4 5]]]]]


In [6]:
e = np.array([3,2,8,7,5])

print( "E array index 0: ", e[0]) #prints out 3 because array indexing starts at 0

E array index 0:  3


In [7]:
f = np.array([[1,2,3], [4,5,6]])

print("F array index 0,1: ", f[0,1]) #prints out 2
print("F array index 1,0: ", f[1, 0]) #prints out 4
print("Last element of the 2nd row", f[1, -1]) #prints out 6

F array index 0,1:  2
F array index 1,0:  4
Last element of the 2nd row 6


In [8]:
g = np.array([5,6,2,9,8,7,7])

print("G array index 1 to 4: ", g[1:5]) #it starts from index 1 until 5, but doesnt include index 5. weird
#in a nutshell it includes the start index, but excludes the end index

print("G array from index 4 till the end: ", g[4:]) #slices arrays from index 4 till the end

print("G array from index 0 till 3: ", g[:4]) #index 4 is not included

print("G array index 3 from the end to index 1 from the end: ", g[-3:-1])
#note: when backward indexing, the first from the back is -1

print("G array from 1 to 4 with step 2: ", g[1:6:2])

print("Return every other element from the entire G array: ", g[::2])

G array index 1 to 4:  [6 2 9 8]
G array from index 4 till the end:  [8 7 7]
G array from index 0 till 3:  [5 6 2 9]
G array index 3 from the end to index 1 from the end:  [8 7]
G array from 1 to 4 with step 2:  [6 9 7]
Return every other element from the entire G array:  [5 2 8 7]


# COPY and VIEW
Copy allows creation of a new array which is a copy from an existing array. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.


View references an array, but is not a new array. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
#this is copy
h = np.array([5,4,3,2,1])
x = h.copy()
h[0] = 10

print("H array: ", h)
print("Copy of h: ", x)

H array:  [10  4  3  2  1]
Copy of h:  [5 4 3 2 1]


In [10]:
j = np.array([5,6,7,8,9])
y = j.view()
j[0] = 1

print("Isi array j: ", j)
print("View dari j: ", y)

Isi array j:  [1 6 7 8 9]
View dari j:  [1 6 7 8 9]


# ARRAY SHAPE

In [ ]:
k = np.array([[1,2,3], [1,2,3]])

print(k.shape) # it prints out 2 dimension values where the first dimension has 2 element and the second has 3 elements

(2, 3)


# RESHAPING

In [5]:
l = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(l)
print(l.reshape(4,3)) #turns it into 2 dimensional
#has 4 arrays with 3 elements each

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(m)
print(m.reshape(2,3,2)) #turns it into 3 dimensional
#has 2 arrays where inside also has 3 arrays and inside that has 2 elements

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
print(m.reshape(2,3,2).base)
#returns the original array thus it is a view

[ 1  2  3  4  5  6  7  8  9 10 11 12]
