In [25]:
diction = {
    "name": "Razzan Naufal Rianta",
    "age": 20,
    "matkuls": ["Embedded Systems", "Cloud", "Fault Tolerant"]
} # this is a dictionary

print(diction["name"]) # access the dictionary with square brackets

x = diction.get('matkuls') # also like this
print(x)

Razzan Naufal Rianta
['Embedded Systems', 'Cloud', 'Fault Tolerant']


In [26]:
print(diction.keys()) # gets all the keys of the dictionary
print(diction.values()) # gets all the values of the dictionary

dict_keys(['name', 'age', 'matkuls'])
dict_values(['Razzan Naufal Rianta', 20, ['Embedded Systems', 'Cloud', 'Fault Tolerant']])


In [27]:
# updating the values
print(diction['name']) # before change
diction["name"] = "Test man"
print(diction['name']) # after change

# OR

diction.update({"age": 21})
print(diction["age"])

# hey neat trick below

put = "age"
diction.update({put: 30})
print(diction["age"])

Razzan Naufal Rianta
Test man
21
30


In [13]:
# adding new items
diction['newThing'] = "idk" # just like normal

print(diction['newThing'])

idk


In [14]:
# removing items
diction.pop("newThing") # removes a specific value
print(diction)

{'name': 'Test man', 'age': 30, 'matkuls': ['Embedded Systems', 'Cloud', 'Fault Tolerant']}


In [15]:
# another way of removing items
diction.popitem() # removes the last item in the dictionary
print(diction)

{'name': 'Test man', 'age': 30}


In [16]:
# delete a dictionary completely
del diction

In [21]:
# clearing a dictionary

thisdict = {
    "thing": "Hello world",
    "otherThing": 70
}

print(thisdict)

{'thing': 'Hello world', 'otherThing': 70}


In [32]:
# looping in a dictionary
print("Keys in a dictionary: ")
for x in thisdict:
    print(x)

print("\nValues in a dictionary: ")
for x in thisdict:
    print(thisdict[x])

print("\nValues in a dictionary (other way): ")
for x in thisdict.values():
    print(x)

print("\nLoop through the keys and values: ")
for x, y in thisdict.items():
    print(x, y)

Keys in a dictionary: 
thing
otherThing

Values in a dictionary: 
Hello world
70

Values in a dictionary (other way): 
Hello world
70

Loop through the keys and values: 
thing Hello world
otherThing 70


In [33]:
# copy
newdict = thisdict.copy()
print(newdict)

{'thing': 'Hello world', 'otherThing': 70}


In [35]:
child1 = {
    "name": "Siti",
    "age": 10
}

child2 = {
    "name": "Budi",
    "age": 20
}

child3 = {
    "name": "Udin",
    "age": 15
}

parent = {
    "child1": child1,
    "child2": child2,
    "child3": child3
}

for key, val in parent.items():
    print(f"\nThis is {key}")
    for x in val:
        print(f"{x}: {val[x]}")


This is child1
name: Siti
age: 10

This is child2
name: Budi
age: 20

This is child3
name: Udin
age: 15


# UNRELATED NOTES

In [ ]:
# an unrelated note
a = 10 # give 'a' a value
b = a # copy a into b
b = 20 # change b into 20
print(a) # prints 10

c = [10,20] # gives c the following list value
d = c # references c into d
d.append(100) # append 100 into d
print(c) # print 10,20,100

10
[10, 20, 100]


# references

in python, instead of pointers there are references. it is just using an equals to sign. that's it. BUT it only works for mutable objects like dictionaries, list, tuples, object instances of classes, etc. immutable objects like int, float, bool, string, etc, cannot be referenced. lets try it shall we

In [ ]:
class Node:
    def __init__(self, data, right=None, left=None):
        self.data = data
        self.right = right
        self.left = left

class BinaryTree:
    def __init__(self):
        self.root = None
        self.size = 0
    
    def __sisipDt(self, input, node):
        if self.root == None:
            self.root = Node(input)
            self.size += 1
        else:
            if input >= node.data:
                if node.right == None:
                    node.right = Node(input)
                    self.size += 1
                else:
                    self.__sisipDt(input, node.right)
            elif input < node.data:
                if node.left == None:
                    node.left = Node(input)
                    self.size += 1
                else:
                    self.__sisipDt(input, node.left)
    
    def __preorderDt(self, node):
        if node is None:
            return 
        print(node.data)
        self.__preorderDt(node.left)
        self.__preorderDt(node.right)
    
    def __inorderDt(self, node):
        if node is None:
            return 
        self.__inorderDt(node.left)
        print(node.data)
        self.__inorderDt(node.right)
    
    def __postorderDt(self, node):
        if node is None:
            return 
        self.__postorderDt(node.left)
        self.__postorderDt(node.right)
        print(node.data)
    
    def sisipData(self, input):
        self.__sisipDt(input, self.root)
    
    def preorder(self):
        self.__preorderDt(self.root)
    
    def inorder(self):
        self.__inorderDt(self.root)
    
    def postorder(self):
        self.__postorderDt(self.root)

tree = BinaryTree()

tree.sisipData(30)
tree.sisipData(40)
tree.sisipData(5)
tree.sisipData(10)
tree.sisipData(15)
tree.inorder()

5
10
15
30
40


In [10]:
import numpy as np
np.random.seed(0)

A = np.array([
    [1,2.5,-3,1],
    [4,-9,-1,6],
    [6,-5,-2,-7]
])

B = np.array([1,2,3,4])
print(np.zeros((1, 4)))

[[0. 0. 0. 0.]]


In [14]:
import numpy as np

np.random.seed(0)

X = np.array([
    [1,2.5,-3,1],
    [4,-9,-1,6],
    [6,-5,-2,-7]
])

class Layer_Dense:
    def __init__(self, n_input, n_neuron):
        self.weights = 0.2 * np.random.randn(n_input, n_neuron)
        self.biases = np.zeros((1, n_neuron))
    def forward(self, input):
        self.output = np.dot(input, self.weights) + self.biases

layer1 = Layer_Dense(4, 6)
layer1.forward(X)
print(layer1.output)

[[ 0.43384558 -0.23947132 -0.63277773  0.58399701 -0.27802682  0.50634313]
 [-0.07544358 -0.45668115 -2.18357611  1.7712447   1.97327559 -4.24908099]
 [ 0.42406453  1.77860989  4.67434488  1.22993757  0.28918371 -1.50591263]]
